spring:
  application:
    name: back
  datasource:
    url: jdbc:postgresql://localhost:5432/startup?currentSchema=startup
    username: postgres
    password: password
  liquibase:
    change-log: classpath:db/db.changelog.xml
    enabled: true